services:
  mcpo-simple-server:
    hostname: mcpo-simple-server
    container_name: mcpo-simple-server
    image: ghcr.io/getsimpletool/mcpo-simple-server:latest
    shm_size: '2gb'
    #build:
    #  context: ..
    #  dockerfile: ./docker/Dockerfile
    ports:
      - 2222:22       # SSH port
      - 8000:8000     # API HTTP MCPoSimpleServer port
      - 5901:5901     # VNC port
      - 6901:6901     # HTTP noVNC port
    # Set limit CPU core = 2
    cpus: '2'
    # Set limit memory = 3GB
    mem_limit: '3g'
    environment:
      - PUID=1000
      - PGID=100
      - TZ=CET
    env_file:
      - mcpo-simple-server.env
    volumes:
      - data:/app/mcpo_simple_server/data
    restart: unless-stopped

networks:
  default:
    name: simpletool

# Create volume for data
volumes:
  data:
    name: simpletool-server-data
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/
