services:
  simpletoolserver:
    hostname: simpletoolserver
    container_name: simpletoolserver
    image: ghcr.io/getsimpletool/simpletool-server:latest
    shm_size: '2gb'
    #build:
    #  context: ..
    #  dockerfile: ./docker/Dockerfile
    ports:
      - 2222:22       # SSH port
      - 8000:8000     # HTTP SimpleTool MCP port
      - 5901:5901     # VNC port
      - 6901:6901     # HTTP noVNC port
    # Set limit CPU core = 2
    cpus: '2'
    # Set limit memory = 3GB
    mem_limit: '3g'
    environment:
      # --- Core ENV used by the server ---
      - ADMIN_DEFAULT_PASSWORD=admin # Admin password for first user. Default: admin
      - ADMIN_BEARER_HACK=abc123 # Static Bearer token for admin. Default: unset (empty)
      - SALT=default_insecure_pepper # Used for password hashing. Default: default_insecure_pepper
      - JWT_SECRET_KEY=default_insecure_secret_key # JWT secret. Default: default_insecure_secret_key
      - JWT_ALGORITHM=HS256 # JWT algorithm. Default: HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30 # JWT access token expiry (minutes). Default: 30
      - CONFIG_STORAGE_TYPE=files # Config storage type. Default: files
      #- TOOL_CONFIG_PATH=/app/server/data/config/config.json # Tool config path. Default: $APP_FOLDER/data/config/config.json
      #- CONFIG_STORAGE_PATH=/app/server/data/config # Path to config storage. Default: $APP_FOLDER/data/config
      - PRIVATE_SERVER_CLEANUP_INTERVAL=300 # Idle private server cleanup interval (seconds). Default: 300
      - TOOLS_WHITELIST= # Comma-separated list of tools to whitelist. Default: unset (empty)
      - TOOLS_BLACKLIST= # Comma-separated list of tools to blacklist. Default: unset (empty)
      - SUBPROCESS_STREAM_LIMIT=5242880 # Subprocess stream limit in bytes (default: 5MB)
      - SSH_ENABLED=true # Enable SSH. Default: true
      - VNC_ENABLED=true # Enable VNC. Default: true
      # --- System-level ENV (optional, not used by server code) ---
      - PUID=1000
      - PGID=1000
      - TZ=CET
    volumes:
      - data:/app/server/data
    restart: unless-stopped

networks:
  default:
    name: simpletool


volumes:
  data:
    name: simpletool-server-data    
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data
