name: Build Docker Image

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          file: ./docker/Dockerfile
          context: .
          push: false
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.ref_name }}

      - name: Image built
        run: echo "Docker image build completed"
