name: Release
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag (e.g. v0.1.1)'
        required: true
        type: string
      release_tag_latest:
        description: 'Alias tag as latest'
        required: false
        type: boolean
        default: true
      push_image:
        description: 'Push image to GHCR'
        required: false
        type: boolean
        default: true

jobs:
  test:
<<<<<<< HEAD
    uses: ./.github/workflows/reusable/reusable-test.yml
=======
    uses: ./.github/workflows/reusable-test.yml
>>>>>>> d0488d8 (v0.1.2)

  build-docker:
    needs: test
    if: ${{ needs.test.result == 'success' }}
<<<<<<< HEAD
    uses: ./.github/workflows/reusable/reusable-build-docker.yml
=======
    uses: ./.github/workflows/reusable-build-docker.yml
>>>>>>> d0488d8 (v0.1.2)
    with:
      release_tag: ${{ github.event_name == 'release' && github.event.release.tag_name || github.event.inputs.release_tag }}
      release_tag_latest: ${{ github.event_name == 'release' && true || github.event.inputs.release_tag_latest }}
      push_image: ${{ github.event_name == 'release' && true || github.event.inputs.push_image }}
