name: Release
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag (e.g. v0.1.1)'
        required: true
        type: string
      release_tag_latest:
        description: 'Alias tag as latest'
        required: false
        type: boolean
        default: true
      push_image:
        description: 'Push image to GHCR'
        required: false
        type: boolean
        default: true

permissions:
  contents: read
  packages: write

jobs:
  test:
    uses: ./.github/workflows/reusable-test.yml
  build-docker:
    needs: test
    if: ${{ needs.test.result == 'success' }}
    uses: ./.github/workflows/reusable-build-docker.yml
    permissions:
      contents: read
      packages: write
    with:
      release_tag: ${{ github.event_name == 'release' && github.event.release.tag_name || github.event.inputs.release_tag }}
      release_tag_latest: ${{ github.event_name == 'release' && true || github.event.inputs.release_tag_latest }}
      push_image: ${{ github.event_name == 'release' && true || github.event.inputs.push_image }}
