# Reusable workflow: pytest
# Purpose: Run all server pytest (Python+Node) on multiple Python versions. Used by CI and release pipelines.
# Inputs: none
# Usage example:
#   jobs:
#     pytest:
#       uses: ./.github/workflows/reusable-pytest.yml

name: reusable-pytest
on:
  workflow_call:

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11', '3.12', '3.13', '3.14']
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install setuptools
          pip install -r src/mcpo_simple_server/requirements.txt
          pip install -r tests/server/requirements-pytest.txt
          uv --version

      - name: Run pytest with --clean
        working-directory: ./tests/server
        run: bash run.sh a --clean
