# Reusable workflow: build-docker
# Purpose: Build and push Docker image to GHCR using provided release tag. Optionally push as 'latest'.
# Inputs:
#   release_tag (string, required): Docker image tag (e.g. v0.1.1)
#   release_tag_latest (boolean, required): Whether to also tag/push as 'latest'
#   push_image (boolean, optional, default: false): Whether to actually push the image to the registry
# Usage example:
#   jobs:
#     build-docker:
#       uses: ./.github/workflows/reusable/reusable-build-docker.yml
#       with:
#         release_tag: ${{ github.event.release.tag_name }}
#         release_tag_latest: true
#         push_image: true

name: reusable-build-docker
on:
  workflow_call:
    inputs:
      release_tag:
        required: true
        type: string
      release_tag_latest:
        required: true
        type: boolean
      push_image:
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set Docker tags
        id: docker_tags
        run: |
          RELEASE_TAG="ghcr.io/${{ github.repository_owner }}/simpletool-server:${{ inputs.release_tag }}"
          if [ "${{ inputs.release_tag_latest }}" = "true" ]; then
            LATEST_TAG="ghcr.io/${{ github.repository_owner }}/simpletool-server:latest"
            ALL_TAGS="$RELEASE_TAG,$LATEST_TAG"
          else
            ALL_TAGS="$RELEASE_TAG"
          fi
          echo "release_tag=$RELEASE_TAG" >> $GITHUB_OUTPUT
          echo "latest_tag=${LATEST_TAG:-}" >> $GITHUB_OUTPUT
          echo "all_tags=$ALL_TAGS" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          file: ./docker/Dockerfile
          context: .
          push: ${{ inputs.push_image }}
          tags: ${{ steps.docker_tags.outputs.all_tags }}
          build-args: |
            APP_VERSION=${{ inputs.release_tag }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/simpletool-server:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/simpletool-server:buildcache,mode=max

      - name: Image built
        run: echo "Docker image build completed for"
