# Reusable workflow: test
# Purpose: Run all server tests (Python+Node). Used by CI and release pipelines.
# Inputs: none
# Usage example:
#   jobs:
#     test:
#       uses: ./.github/workflows/reusable/reusable-test.yml

name: reusable-test
on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install setuptools
          pip install -r src/mcpo_simple_server/requirements.txt
          pip install -r test/server/requirements-pytest.txt

      - name: Install uv (Python package manager)
        run: |
          pip install uv
          uv --version

      - name: Run pytest with --clean
        working-directory: ./test/server
        run: pytest --clean
